### ISSUE TITLE
Unable to upgrade to slf4j 2.x

### ISSUE THREAD

**Issue by mvfranz** [OpenHFT/Chronicle-Logger#112]
I am able to use the slf4j 1.7.22 to generate logs using chronicle logger. When I upgrade to slf4j to 2.0.3 I get the following error:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/user/.gradle/caches/modules-2/files-2.1/net.openhft/chronicle-logger-slf4j/4.22ea2/c427ed8d94520a0230231905bd1b37cea411b1ce/chronicle-logger-slf4j-4.22ea2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```
It seems that the loading mechanism for slf4j has changed in the 2.x release.  Will chronicle logger be supporting this change?  The chronicle logger documentation state is supports slf4j 1.7 and above, but I assume that was written prior to the 2.x changes.

**Comment by mvfranz** [comment]
I have created a PR to address this issue. I did not find any documentation that covers the procedure to contribute to this project. Can someone point me to the process?

**Comment by JerryShea** [comment]
Thanks @mvfranz . Contributors need to sign the [CLA](https://chronicle.software/contributor-agreement/). Once this is done we will review, provide feedback, and merge.

To set expectations though, we are very busy with client work, and no-one else has asked for this, so it may take us some time to review.

**Comment by mvfranz** [comment]
> Thanks @mvfranz . Contributors need to sign the [CLA](https://chronicle.software/contributor-agreement/). Once this is done we will review, provide feedback, and merge.
> 
> To set expectations though, we are very busy with client work, and no-one else has asked for this, so it may take us some time to review.

I have submitted the CLA.

**Comment by JerryShea** [comment]
Thanks @mvfranz this is now merged and a new version of Chronicle-Logger will be released soon
