### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by hendrikebbers** [OpenHFT/Chronicle-Logger#130]
Hi,

I created a project to measure the performance of Java loggers. The project uses JMH and measures the performance on different machines and configurations. You can find the results here: https://github.com/OpenElements/java-logger-benchmark

For some setups (Linux box with 40 vCPUs, 250 GB RAM, local SSD, 240 threads logging) the performance of Chronicle-Logger is really bad. You can find the results on the README of the project. Can you have a look at the repo and check if I did anything wrong. I do not want that numbers to be shared widely before you had a change to check if that is correct.

**Comment by peter-lawrey** [comment]
Thank you for the feedback., I will look into it by tomorrow.

**Comment by peter-lawrey** [comment]
Sent a PR https://github.com/OpenElements/java-logger-benchmark/pull/1

You should be able to run the ChronicleTest with 128 MB heap easily.

**Comment by hendrikebbers** [comment]
Thank you. I will update everything
