### ISSUE TITLE
Configuration bug when using logback along with chronicle-logger

### ISSUE THREAD

**Issue by Mark-Yin** [OpenHFT/Chronicle-Logger#24]
Hello
    When I use logback.xml to configure the appender settings of class "net.openhft.chronicle.logger.logback.BinaryVanillaChronicleAppender", there is an issue that property dataBlockSize can not be recognized by logback while indexBlockSize works. I tracked down the source code and found out that when logback is building Bean information from "Introspector.getBeanInfo(obj.getClass())", only the readMethod of dataBlockSize exists and the writeMethod can not be found. By this, an error message will be thrown out: 

ERROR in ch.qos.logback.core.joran.spi.Interpreter@28:19 - no applicable action for [dataBlockSize], current ElementPath  is [[configuration][appender][chronicleConfig][dataBlockSize]]
    I think the root cause is the type error of dataBlockSize in the class VanillaLogAppenderConfig

    public long getDataBlockSize() {
        return this.builder.dataBlockSize();
    }

    //TODO: long vs int
    public void setDataBlockSize(int dataBlockSize) {
        this.builder.dataBlockSize(dataBlockSize);
    }

    The getter and setter should have the same type of variable in order to make Bean construction method work correctly.

Regards,
Mark

**Comment by BoundedBuffer** [comment]
thanks for your email - JIRA raised - https://higherfrequencytrading.atlassian.net/browse/CLOG-32 <https://higherfrequencytrading.atlassian.net/browse/CLOG-32>

**Comment by lburgazzoli** [comment]
The fix has been implemented in the latest 1.1.0-SNAPSHOT.
Thank you for spotting this.

**Comment by Mark-Yin** [comment]
The setting of dataBlockSize in BinaryVanillaAppender works again. Thanks for solving the issue so quickly.
