### ISSUE TITLE
Serialization of exceptions

### ISSUE THREAD

**Issue by alexvictoor** [OpenHFT/Chronicle-Logger#26]
Hello
This ticket is related to the comments of former ticket 15
When a binary appender is used, an exception is serialized with serializer "JDKZObjectSerializer". This implies that you cannot read logs if you do not have in your classpath the exception classes that have been used by the application that has generated the logs.
This forbid to use ChroniTail, ChroniCat and the other tools working as standalone tools...
Also this almost forbid applications to refactor their exception classes.
Instead of serializing the exception itself, I think that the logger should serialize an object containing two strings: 
1. the exception message
2. the exception stack trace as a string

**Comment by peter-lawrey** [comment]
I think this is a reasonable approach.

Longer term, I would like to serialize an Exception in a text form which
allows deserialization, however can be read without the class which created
it.

**Comment by lburgazzoli** [comment]
It is reasonable for exceptions but it doesn't for other objects so if you call logger.info("got {}", obj, except) to a binary appender , exception will be always readable but obj won't unless you have it in the class-path. The simplest way to have an 'open' log is to use a TextAppendet which format the message and serialized exceptions as strings. 

I can easily add an option to serialize exception as strings but as mentioned above, non simple objects require the class to be available, is that an acceptable limitation? 

I can also add an option to chronicle to serialize objects without compression.

**Comment by alexvictoor** [comment]
Thanks for your responses
Is there any doc on how works a binary chronicle/appender vs a text one?
I have done a few tests and even when i just log a string, the binary appender is much faster than the text one. I do not get why? Compression is done by default?

**Comment by lburgazzoli** [comment]
Not at the moment but I will document the difference between binary and text as soon as possible. 

The main difference is that binary use buffer.write(...) wich write bytes (i.e. 4 bit for an int) whereas text uses buffer.append(...) which write thing in a human readable form (similar to append strings); in addition the TextAppender need to format the message (i.e. the logback appender invokes ILoggingEvent.getFormattedMessage).

Yes at the moment compression is done by default, I will add an option to Chronicle V3 to disable it.

**Comment by alexvictoor** [comment]
Thanks!
much more clear now. I was not aware that I could use the Externalizable interface and did not know  BytesMarshallable and DataValueClasses...
BTW next month I will do a talk at [devoxx france](http://cfp.devoxx.fr/2015/talk/UQF-3859/Un_monde_ou_1_ms_vaut_100_M%E2%82%AC) and I will talk a little bit of openhft :+1:

**Comment by lburgazzoli** [comment]
@alexvictoor can we close this issue ?
