### ISSUE TITLE
Example of Logs aggregation

### ISSUE THREAD

**Issue by yzhishko** [OpenHFT/Chronicle-Logger#42]
I have several machines with 3 apps running on each. Each app is writing logs on local machine. I want to make all apps to write on a remote machine to a common storage. How can I configure Chronicle Logger to do that?

**Comment by peter-lawrey** [comment]
This is not currently supported as Chronicle Logger is based on Chronicle Queue v3.x
We might support this when we update to Queue 4.x

**Comment by 243826** [comment]
@peter-lawrey Is this supported now?

**Comment by dpisklov** [comment]
It's supported but not by logger itself.
We have enterprise version of a Queue which includes replication, so all logs from all machines can be replicated over to centralized log server. If you are interested in that please contact sales@chronicle.software
