### ISSUE TITLE
Is Chronicle Logger compatible with Chronicle Queue v4?

### ISSUE THREAD

**Issue by MartyIX** [OpenHFT/Chronicle-Logger#45]
Hi,

I'm trying to setup Chronicle Logger 1.1.1:

1) `build.gradle`:
```
compile group: 'net.openhft', name: 'chronicle-logger-logback', version: '1.1.1'
```

2) `logback.xml`:
```
    <appender name  = "PERFORMANCE_FILE_CQ4"
              class = "net.openhft.chronicle.logger.logback.TextVanillaChronicleAppender">
        <path>${dataFolder:-data}/performance</path>
        <formatMessage>false</formatMessage>
        <includeCallerData>false</includeCallerData>
        <includeMappedDiagnosticContext>false</includeMappedDiagnosticContext>
        <chronicleConfig>
            <dataCacheCapacity>1</dataCacheCapacity>
        </chronicleConfig>
    </appender>
```

and Logback really creates `data/performance` folder. However, it creates new and new files like this:

![image](https://user-images.githubusercontent.com/203266/27479516-83171366-5814-11e7-8a8a-98b925ea833f.png)

I'm not really sure what happens. My expectation was that one file would be created.

Thank you for any help

Regards,
Martin

**Comment by dpisklov** [comment]
@MartyIX 
Current Chronicle-Logger master (3.x) uses Chronicle 3.x, hence the files you noticed.
There's a branch 4.x which is upgrade to Chronicle Queue 4.x, and it's pretty much finished. Soon we will replace master with 4.x and deprecate 3.x.
