### ISSUE TITLE
Using Logstash with Chronicles-Logger (Logback)

### ISSUE THREAD

**Issue by msiddiqi** [OpenHFT/Chronicle-Logger#46]
Hi, We are currently using ELK Stack (Elastic Search / Logstash / Kibana). We use Logstash TCP appender with logback to push these logs to Logstash in our Scala projects. Is there a way, we use the current logging stack with Chronicle-Logger?

P.S. I have used chronicles-logger (version 1.1.1) from http://repo.spring.io/libs-milestone/ repository. 

Thanks,
Muhammad

**Comment by TerryW9** [comment]
Hi Muhammad,

Thank you for your question.
We will try to get back to you with an answer as soon as possible.

Best Regards,
Terry

**Comment by epickrram** [comment]
Hi Muhammad, 
what problem are you trying to solve by using chronicle-logger? From what I understand of your stack, you already asynchronously log messages (via logback), that are then sent over the network to Logstash.
Are you trying to reduce the amount of garbage generated by the log messages?

**Comment by msiddiqi** [comment]
Actually just trying to see what different components chronicles provides and see how we can use in our environment. "Fast synchronous logging without losing any message before an service crashed" is what I am interesting in here. This should be specially useful for some low latency trade execution related work we are planning to do in future.

**Comment by epickrram** [comment]
The main difference if you use chronicle-logger is that your log messages will be persisted to disk on the local machine. Persistence via chronicle-queue will faster than writing to a standard file, and you can choose a more compact/efficient format (i.e. BINARY) for storing the messages.

The drawback of this approach is that you no longer have all your log messages in a single place for easy searching. If that is still a requirement, then you'd need to create another component/process to read the log files and send them off to logstash. In a crash scenario, you'd then need to make sure you don't send duplicate log entries to logstash on restart.

If you'd like some support in designing a solution, Chronicle Software can provide consultancy services to help you get the most out of the open-source products. You can find contact details on the website:

http://chronicle.software
