### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by MartyIX** [OpenHFT/Chronicle-Logger#50]
Hi,

Log4j2 provides for its appenders possibility to compress log files after roll overs. Does Chronicle Queue support anything similar? Can I emulate it somehow?

Thanks

Regards,
Martin

**Comment by dpisklov** [comment]
@MartyIX 
hi Martin, the purpose of Chronicle Logger is to be (1) fast and (2) produce as little garbage as possible. 
Compression adds significant CPU load, and if done asynchronously also will produce garbage. The best thing I can suggest if you really have space issues is cron job running at idle time (say, after market close and before market open) compressing cq4 files. They usually compress fairly well. This however will make it harder for you to look through the whole history, as a tradeoff.

**Comment by MartyIX** [comment]
@dpisklov Yes, I understand the objectives of the library. I just don't know if I can compress cq4 after a rollover as I'm not sure if it may break my app. I can try but I know only little about the codebase to know if it is fundamentally wrong approach or not.

Thank you for your reply

**Comment by dpisklov** [comment]
@MartyIX
Chronicle Logger uses normal Chronicle Queue as a storage. If nothing is reading from the old file (and logger itself never reads anything - only writes), it is safe to compress it. That is, after the log rolled to the new file, it will only write to the new file. If you subsequently compress the old file, and then will create a tailer (or just use one of the log processing tools supplied) it will only read starting from the earliest available file, ignoring compressed one. Shall you wish to browse through compressed file however, you will need to uncompress it to temp directory.

HTH

**Comment by MartyIX** [comment]
Thank you! That's great.

**Comment by dpisklov** [comment]
You are welcome!
