### ISSUE TITLE
logging an arbitrary object using Chronicle logger throws IllegalStateException

### ISSUE THREAD

**Issue by gjajoo** [OpenHFT/Chronicle-Logger#51]
When attempting to use the slf4j facade with Chronicle logger we're running into an IllegalStateException which can be traced to ValueOut.java in chronicle wire.

            throw new IllegalStateException("type=" + value.getClass() +
                    " is unsupported, it must either be of type Marshallable, String or " +
                    "AutoBoxed primitive Object");

Slf4j (and log4j/logback) don't have any restriction on the object type that gets logged. In absence of known serializability those libraries seem to just invoke .toString(). Unfortunately the code that logs the arbitrary objects is a library code that we don't have control over. Is there a way to configure Chronicle logger to support logging of arbitrary objects using toString?

**Comment by gjajoo** [comment]
Thanks for the quick fix. When do you expect the next release to be?

**Comment by dpisklov** [comment]
@gjajoo 4.1.0 released
