### ISSUE TITLE
Bump log4j2 version

### ISSUE THREAD

**Issue by sheinbergon** [OpenHFT/Chronicle-Logger#53]
Hello.

The version of log4j2 you're built against is using log4j2 2.8.x, which is rather old and under-performing (twice as slow using similar setups).

If you could please update the log4j2 version to 2.10 ( Spring 2.0.x compatibility here is a major plus). Versions are binary/code wise incompatible, so it's not just a matter of dependency exclusion/override.

10x

**Comment by dpisklov** [comment]
Done. Ignore the commit referenced here - the real change is in third-party-bom.
This will be in next 4.0.2 version.

**Comment by sheinbergon** [comment]
@dpisklov great. When is the next version (4.0.2) planned?

**Comment by dpisklov** [comment]
4.0.3 is now released.
