### ISSUE TITLE
Chronicle-Logger rollover to compressed file(gzip)

### ISSUE THREAD

**Issue by SPSiva153** [OpenHFT/Chronicle-Logger#56]
Hi,

I am using chronicle-logger-log4j-2 to log the messages and I need to rollover .cq4 files every 1000MB and compress them same as File logger. But I don't find the configuration to achieve this.

Is there a way to configure Chronicle logger to achieve this?

**Comment by dpisklov** [comment]
Chronicle-Queue (which is what cq4 files are) doesn't support rolling by file size, only time-based.

**Comment by SPSiva153** [comment]
If it supports time-based rolling, can we rollover every hour and how it can be achieved like filelogger? Below by xml configuration,

     <Properties>
        <Property name="name">chronicle-queue</Property>
        <Property name="logPath">logs/chronicle-log4j2/</Property>
        <Property name="pattern">[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n</Property>
    </Properties>    

    <Appenders>
        <Chronicle name="CHRONICLE">
            <path>${logPath}chronicle</path>
        </Chronicle>

        <RollingFile name="File" fileName="${logPath}${name}.log"
                     filePattern="${logPath}/${name}-%d{yyyy-MM-dd}-%i.log.gz">
            <PatternLayout pattern="${pattern}"/>
            <Policies>
                <TimeBasedTriggeringPolicy interval="3600" modulate="true"/>
                <SizeBasedTriggeringPolicy size="100MB"/>
            </Policies>
            <DefaultRolloverStrategy max="10"/>
        </RollingFile>
    </Appenders>

**Comment by hft-team-city** [comment]
Released in [Chronicle-Logger-4.19.30](https://github.com/OpenHFT/Chronicle-Logger/releases/chronicle-logger-4.19.30), [BOM-2.19.184](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.184)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Logger-4.19.30](https://github.com/OpenHFT/Chronicle-Logger/releases/chronicle-logger-4.19.30), [BOM-2.19.185](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.185)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Logger-4.19.30](https://github.com/OpenHFT/Chronicle-Logger/releases/chronicle-logger-4.19.30), [BOM-2.19.187](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.187)
