### ISSUE TITLE
chronicle-logger 4.17.2 pom.xml is referencing non-existing version of chronicle-bom

### ISSUE THREAD

**Issue by danke02** [OpenHFT/Chronicle-Logger#58]
Hello.
I tried to get chronicle-logger and its related libraries with maven.
There was an error and I found that it is referencing non-existing version 2.17.172 chronicle-bom.
I manually modified version of chronicle-bom to 2.17.298 of local pom.xml and now it works.
Please check it out.
Thank you.

**Comment by dpisklov** [comment]
Not sure what you mean by non-existing bom.
2.17.172 bom is available on maven-central:
https://search.maven.org/artifact/net.openhft/chronicle-bom/2.17.272/pom
https://repo1.maven.org/maven2/net/openhft/chronicle-bom/2.17.272/

**Comment by danke02** [comment]
> Not sure what you mean by non-existing bom.
> 2.17.172 bom is available on maven-central:
> https://search.maven.org/artifact/net.openhft/chronicle-bom/2.17.272/pom
> https://repo1.maven.org/maven2/net/openhft/chronicle-bom/2.17.272/

your link is 272 not 172

**Comment by dpisklov** [comment]
It does now. Not sure how it disappeared.

**Comment by danke02** [comment]
> It does now. Not sure how it disappeared.

Okay, now 172 directory exists. Thanks!
