### ISSUE TITLE
How to append extended information to logger 

### ISSUE THREAD

**Issue by luxapana** [OpenHFT/Chronicle-Logger#74]
I wish to include traceid/spanid which are injected from opentelemetry instrumentation to logs. The console Appender can be configured as follows to do this:

```
<Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} traceId: %X{trace_id} spanId: %X{span_id} - %msg%n" />
        </Console>
```

And it outputs something like this:

`15:19:24.154 [main] DEBUG MyApp traceId: b19e837e754e1cae22355f807f65c05d spanId: a82dd9d711431773 - Entering application.`

How can I achieve this with chronicle logger? I do not wish to change existing log statements as some of the required logs are coming from third party libraries.

**Comment by luxapana** [comment]
Some help is much appreciated @lburgazzoli @peter-lawrey

**Comment by peter-lawrey** [comment]
Chronicle-Logger is just a different destination for logs, the same library features should work.

**Comment by tgd** [comment]
Closing this out as no work is planned on this issue at the moment. Please comment on this issue if you would like it re-opened.
