### ISSUE TITLE
fixed test net.openhft.chronicle.logger.jul.JulLoggerChronicleTest

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Logger#99]
see https://teamcity.chronicle.software/viewLog.html?buildId=642270&tab=buildResultsDiv&buildTypeId=OpenHFT_BuildAll_BuildJava11compileJava11

![image](https://user-images.githubusercontent.com/6506056/148463790-9a41bfd4-cd42-48cb-aa04-8f610d76b69a.png)

```
java.lang.AssertionError: expected:<logger> but was:<null>
	at net.openhft.chronicle.logger.jul.JulLoggerChronicleTest.testChronicleConfiguration(JulLoggerChronicleTest.java:58)
	at net.openhft.chronicle.logger.jul.JulLoggerChronicleTest.testChronicleConfig(JulLoggerChronicleTest.java:91)
------- Stderr: -------
Unable to initialize chronicle-logger-jul (logger)
  Unable to claim exclusive exclusive lock on file /tmp/chronicle-jul-api/root-binary/metadata.cq4t
```

**Comment by tgd** [comment]
Closing this out as no work is planned on this issue at the moment. Please comment on this issue if you would like it re-opened.
